global:
  scrape_interval: 5s

scrape_configs:

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3001']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Uncomment if cAdvisor is enabled (Linux/macOS only)
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
